repos:
  # https://docs.franco.net.eu.org/md-toc/pre_commit_hook.html
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.4.0'
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=16384']
      - id: check-case-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
        args: ['--assume-in-merge']
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: no-commit-to-branch
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.50.0'
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.28.0
          - eslint-config-prettier@8.5.0
          - eslint-plugin-svelte@2.30.0
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.3'
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.0
          - eslint-config-prettier@8.5.0
          - prettier-plugin-svelte@2.10.1
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: '2.7.2'
    hooks:
      - id: editorconfig-checker-system
        alias: ec
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: 'v1.1.2'
    hooks:
      # https://github.com/jonschlinkert/markdown-toc
      - id: markdown-toc
        args: [-i, --maxdepth, '3']
